### ISSUE TITLE
[node-v6] Got SyntaxError parsing to JS on Node v6

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/carto#28]
I've discovered one more failing use case:

CartoCSS:

```
#layer0['mapnik::geometry_type'=1] { 
  marker-fill: red;
  marker-width: 10;
}
```

```
> if((8388607 & (1 << ctx.zoom)) && data.mapnik::geometry_type === 1){_value = '#ff0000';}
                                                
SyntaxError: Unexpected token :
    at Object._createFn (/vagrant/repos/Windshaft/node_modules/carto/lib/carto/renderer_js.js:153:12)
    at Object.parse (/vagrant/repos/Windshaft/node_modules/carto/lib/carto/renderer_js.js:245:40)
    at Object.setStyle (/vagrant/repos/Windshaft/node_modules/carto/lib/carto/renderer_js.js:120:23)
    at Object.CartoCSS (/vagrant/repos/Windshaft/node_modules/carto/lib/carto/renderer_js.js:10:10)
    at render (/vagrant/repos/Windshaft/node_modules/carto/lib/carto/renderer_js.js:280:12)
    at Object.module.exports.optionsFromCartoCSS (/vagrant/repos/Windshaft/lib/windshaft/utils/cartocss_utils.js:13:41)
    at /vagrant/repos/Windshaft/lib/windshaft/renderers/mapnik/geojson_renderer.js:20:38
...
```

Also it just happens on Node v6.

**Comment by dgaubert** [comment]
Related to #24

**Comment by dgaubert** [comment]
That issue was resolved in https://github.com/CartoDB/carto/commit/be56e24d9ac6100408caa9be2248bbdfba4c97f2 I've got this exception due to a bad installation from NPM:
```
$ npm ls carto
windshaft@2.7.1 /vagrant/repos/Windshaft
├── carto@0.15.1-cdb1  (git://github.com/cartodb/carto.git#673cf381215948269827052afa152e485b01e2f0)
├─┬ grainstore@1.6.0
│ └── carto@0.16.3
└─┬ torque.js@2.11.5
  └── carto@0.15.1-cdb1  (git://github.com/cartodb/carto.git#8050ec843f1f32a6469e5d1cf49602773015d398)
``` 
which carto points to 0.15.1-cdb1  instead of 0.15.1-cdb2

After publish torque 2.11.5  it points to carto@0.15.1-cdb1 and NPM installs just this version although Windshaft want to use carto@0.15.1-cdb2.

I think NPM does not work well when it finds dependencies that points to github's tag.

cc/ @rochoa

**Comment by dgaubert** [comment]
It fails using NPM 3.10.10 

NPM 2.14.16 works.

**Comment by dgaubert** [comment]
Also it works installing dependencies with yarn@0.21.3.

**Comment by dgaubert** [comment]
And it fails with NPM 4.3.0

**Comment by dgaubert** [comment]
This is really weird:

```
$ npm ls carto
windshaft@2.7.1 /vagrant/repos/Windshaft
├── carto@0.15.1-cdb1  (git://github.com/cartodb/carto.git#673cf381215948269827052afa152e485b01e2f0)
├─┬ grainstore@1.6.0
│ └── carto@0.16.3
└─┬ torque.js@2.11.5
  └── carto@0.15.1-cdb1  (git://github.com/cartodb/carto.git#8050ec843f1f32a6469e5d1cf49602773015d398)
```

It outputs that both windshaft and torque are pointing to carto@0.15.1-cdb1 but the specific commit is not the same. If you check those commits:

 - https://github.com/CartoDB/carto/commits/673cf381215948269827052afa152e485b01e2f0
 - https://github.com/CartoDB/carto/commits/8050ec843f1f32a6469e5d1cf49602773015d398

NPM says that it is using the same version but different commits and those commits point to `0.15.1-cdb2`and `0.15.1-cdb1` respectively. Taking a look into `node_modules`:
 - `carto/package.json`: 
![screen shot 2017-03-06 at 15 46 23](https://cloud.githubusercontent.com/assets/1936888/23614703/31814bba-0284-11e7-8566-05fe8a79fc73.png)

 - `torque/node_modules/carto/package.json`:
![screen shot 2017-03-06 at 15 48 08](https://cloud.githubusercontent.com/assets/1936888/23614765/5cedca6c-0284-11e7-8d7c-b32dc1aacd25.png)

Which seems to have the right metadata but `"_id": "carto@0.15.1-cdb1"`. Furthermore, the code inside both versions is exactly the same: https://github.com/CartoDB/carto/commits/8050ec843f1f32a6469e5d1cf49602773015d398

**Comment by dgaubert** [comment]
Actually is not a issue of `carto` but `npm`. I think I should close this one and open another in the right place (npm??)

**Comment by dgaubert** [comment]
We found the problem: `carto@0.15.1-cdb2` hadn't updated its version of package.json and it had `carto@0.15.1-cdb1`. And NPM 3.10.10 has changed the way that it resolves dependencies returning a bad installation w/o any notice.

Thanks to @rochoa. He was the one to figure out what's going on.
